### PR TITLE
Added php, cause I hate myself

### PR DESCRIPTION
**Pull request by scottshuffler**
:eggplant:

### CODE REVIEW

**Comment by ZhengC1** [comment]
Scott, I appreciate the effort but could you do this in functional PHP? We don't have high standards at ZhengC1/PenisParser, but i don't want to start a server to run this code 😭

**Comment by ZhengC1** [comment]
Also no spaces?

**Comment by ZhengC1** [comment]
though i guess we can add this and still add a functional PHP part later.

**Comment by scottshuffler** [comment]
@ZhengC1 Maybe I'm being silly but I don't see the difference.

Also PHP 5 has a development server built in [See here](http://php.net/manual/en/features.commandline.webserver.php)

**Comment by ZhengC1** [comment]
fine fine, i might change it a bit so it can read and write a file, but 👍 good job.

**Pull request merged**
