### PR TITLE
Added C#

### PR DESCRIPTION
**Pull request by ghost**
Not my proudest moment but this was kinda fun

### CODE REVIEW

**Comment by DV8FromTheWorld** [comment]
Oh interesting, someone actually beat me to the implementation.

**Comment by ZhengC1** [comment]
Hey, i might be running it wrong but doing 'mono penis.exe myFileName.txt' printed penis but did not write the file?

**Comment by ghost** [comment]
Try just 'penis.exe myFileName.txt'

**Comment by ghost** [comment]
Are you running it on linux? I can test it on my vm then I'll tell you how it goes

**Comment by ZhengC1** [comment]
Ah, i was dumb, i saw that it output the Peni, but didn't check for the Result file, this is acceptable. TY

**Pull request merged**
