### PR TITLE
what am i doing with my life

### PR DESCRIPTION
**Pull request by C0urante**
that's it no more for me

### CODE REVIEW

**Comment by Frederik-Baetens** [comment]
Respect man, you've hit rock bottom.

Or have you? There's one more language: malbolge. If you can do this in malbolge i'll give you a euro on paypal.

**Comment by C0urante** [comment]
i'm quitting with what little self-respect i have left, malbolge will have to wait for another

**Comment by C0urante** [comment]
unless you make that a btc instead of a euro, then we might be talking

**Comment by Frederik-Baetens** [comment]
You can get a few dogecoin :p

If i paid you a bitcoin, you'd probably still be working at below hourly wage with the time it would take to write this in malbolge, you'd probably have to write your own code to open files instead of using a library too.

**Pull request merged**
