### PR TITLE
another language. groovy.

### PR DESCRIPTION
**Pull request by C0urante**

### CODE REVIEW

**Comment by DV8FromTheWorld** [comment]
There are no checks to see if the file exists.
Additionally, this regex fails in non-alphanumeric characters and symbols.

**Comment by C0urante** [comment]
I'll add a check for missing files to this and the Clojure PR, and open a new PR for the Haskell and Scala implementations.

RE non-alphanumeric characters: I went by the regex in the original Haskell implementation (but expanded to include all digits and not just '0', which I'm thinking was probably just a bug). I'm not opposed to expanding to a regex that just blacklists characters instead of one that has a whitelist of them, but I like the fact that punctuation is preserved with the current implementation. What would you think about something like `[\S&&[^\p{Punct}]]+` for the regex of strings to replace?

**Comment by DV8FromTheWorld** [comment]
Perhaps a formalization of what should and shouldn't be replaced is in order.
Currently, I am using `\S+` in my implementations, which is to match all characters but whitespace for replacement.
This has the unfortunate effect of matching punctuation as well.

From the few conversations I've had with @ransomts, @WamboJambo, and @ZhengC1, the main goal is word replacement based on whitespace delimitation, so punctuation protection isn't necessarily a requirement based on that current definition. 

As a note, not all languages have regex support, thus making a complex requirement that would effectively require regex might not be smart, hence final recommendation of `\S+`

**Comment by C0urante** [comment]
@DV8FromTheWorld, lgty?

**Pull request merged**
